name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # Runs daily at 18:00 UTC
  workflow_dispatch:        # Allows manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub Contributions
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if git commit -m "🎨 Generated 3D contribution graph"; then
            git push
          fi
